# Generated by Django 2.0 on 2020-05-25 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accueil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Parcours', max_length=100)),
                ('resume', models.TextField()),
                ('description', models.TextField()),
                ('map_url_data', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
